# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy SlackApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        working-directory: ./SlackApp
        run: npm install

      - name: Build TypeScript
        working-directory: ./SlackApp
        run: npm run build

      - name: Prepare files for deployment
        run: |
          # Create a temporary directory for deployment
          mkdir -p temp-deploy

          # Copy only the necessary files to maintain the correct structure
          cp SlackApp/package.json temp-deploy/
          cp SlackApp/package-lock.json temp-deploy/
          mkdir -p temp-deploy/dist
          cp -r SlackApp/dist/* temp-deploy/dist/

          # Copy any other necessary files (e.g., configuration files)
          # If you have other files that need to be included, add them here

          # Create the zip file from the temp directory
          cd temp-deploy
          zip -r ../release-slack.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release-slack.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release-slack.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C436A73215BF4A7493CA3D8151C0E61C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_49702D0434B2465F8C4B53C6E78534CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B90794639BD34386BF35F8B98C060DBA }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chatapp-leewsimpson-slackapp"
          slot-name: "Production"
          package: .
