# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - chatapp-leewsimpson-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        working-directory: ./WebApp
        run: npm install

      - name: Build Next.js application
        working-directory: ./WebApp
        run: npm run build
        env:
          API_URL: http://chatapp-leewsimpson-backend.azurewebsites.net/api/message_stream

      - name: Zip artifact for deployment (only /WebApp)
        run: |
          cd WebApp
          zip -r ../release-webapp.zip .next package.json next.config.ts public -x "node_modules/**"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: release-webapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: unzip release-webapp.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E57EBA494DDB4F8BA933C9C6E517E555 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA28024CCD5440389F59430F36AC6CE4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E21C4BF926C744D99281F8193C434CF6 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "chatapp-leewsimpson-webapp"
          slot-name: "Production"
          package: .
